### ISSUE TITLE
Feature request: add parameter for number of rows to read to impute column type

### ISSUE THREAD

**Issue by markriseley** [hadley/readxl#131]
read_excel works fast in part because it imputes col types on first x rows only (is it 100?). The flipside is it doesn't handle sparse columns well (see this SO post: http://stackoverflow.com/questions/6099243/read-an-excel-file-directly-from-a-r-script).

It would be helpful to expose this parameter to the user eg 'check_len = 100L', perhaps with '-1' to represent check all rows before assigning column types. [should also be applicable to readr::type_convert]

Supplying coltypes in advance may not be practical in some scenarios (eg when parsing file uploads in a shiny application rather than in interactive use).

My current workaround is to use unexported functions eg xlsx_dim to get number of columns (due to #114,#127), then col_types = rep("text",ncol), then type.convert(as.is = T).

Example use case: reading in market research data, where multiple response questions are often coded as either blank or some text representing the response code rather than T/F and can often contain large tracts of blank rows.

**Comment by elastadmin** [comment]
Having the same issue. In my case, the first cell of data in a given column is blank and the actual data only starts at row 150. read_excel assumes it is numeric in data type so when it hit character data, it forces them all to NA. Might be better to default to character datatype if type cannot be inferred. Better to convert a column to the appropriate datatype later than losing data. Pre-specifying datatypes won't work all the time as I don't control the file format sent to me.

**Comment by hangtime79** [comment]
+1 for this feature request:
I followed to this forum from this StackOverflow answer: http://stackoverflow.com/questions/31633891/specifying-column-types-when-importing-xlsx-data-to-r-with-package-readxl 

In a case where there is data sparsity in a column the ability to specify the number of rows in order to determine the column type would be ideal. Based on the StackOverflow answer it appears that ReadXL may be able to get to that easier than others. This would be a great feature to have to an already outstanding package. Thanks for the hardwork!

**Comment by garthtarr** [comment]
+1 for this feature request, `check_len` would be an exceptionally useful parameter!

**Comment by schelhorn** [comment]
+1, urgently needed.

**Comment by schelhorn** [comment]
@hadley, I know you're busy but is there any chance this could be implemented earlier rather than later? Thanks a bunch.

**Comment by tklebel** [comment]
I tried an implementation and created a PR.

Until hadley merges it you can test it out with `devtools::install_github("tklebel/readxl")`.

**Comment by schelhorn** [comment]
Spitze, danke!

**Comment by tklebel** [comment]
My PR does not cover changing the default output to `character`, though I agree with @elastadmin that defaulting to `numeric`, hence possibly loosing information may not be the best solution.

**Comment by sfirke** [comment]
+1. I was about to open a feature request for defaulting to character instead of numeric when the first X rows are all blank and no type is detected.  Easy to coerce to numeric, but today I had one character field that was getting read as numeric and thus all NAs - which necessitated specifying every col_type in the spreadsheet, an annoying slowdown.

(Optionally specifying # of rows to scan when determining col_types would be neat too).

**Comment by jennybc** [comment]
Covered now by #223.
