### ISSUE TITLE
more values for col_types like readr::col_datetime()

### ISSUE THREAD

**Issue by shrektan** [hadley/readxl#135]
Hi, @hadley. I'm wondering why the `readxl::col_types` doesn't have the same possible values like `readr::col_types`, like `col_datetime()`. I think that's really a cool and useful feature. Is it in the plan of future implementing?

Thanks.

**Comment by hadley** [comment]
Definitely.

**Comment by drolejoel** [comment]
May I suggest an abbreviated `col_types` definition style like this. `col_types = "ttnid"` instead of `col_types = c("text", "text", "numeric", "integer", "date")`   This has the advantages of i) being a single string which is a LOT easier to construct manually when you have a >100 columns, ii) being a lot more compact

**Comment by drolejoel** [comment]
Where `readxl::read_excel()` falls down consistently is to guess when the data.frame is sparse e.g., the first 10000 rows are blank. Thus even reading the first 9000 rows won't be able to help discern what the column type should be. Here's a suggestion: perhaps better way is for `readxl::read_excel()` proceed column-by-column as follows: i) sort descending and then ii) read the first N rows.  These first N rows are likely to contain data and it will be easier to tell the type. This really only needs to be done for columns in which the current algorithm has blanks in the Excel file. While this technique is slower, I'm sure it'll be faster than having to manually construct a `col_types` vector, so it might be a good optional argument.  GO HADLEYVERSE!

**Comment by tklebel** [comment]
@drolejoel The case of sparse columns was discussed in #131. Currently, `read_excel` reads the first 100 rows to determine `col_types`. There is a pending pull request which bumps it up to 1000 (#143), and one by me, which implements a parameter to specify the number of rows to be read in order to determine `col_types` (#138). Hadley will likely make bigger changes when he works on readxl again, until then you could use my fork:

```r
devtools::install_github("tklebel/readxl")
read_excel("file.xlsx", n = 10000)
```

**Comment by jennybc** [comment]
Covered by #198
