### ISSUE TITLE
Controlling output of read_excel()

### ISSUE THREAD

**Issue by jennybc** [hadley/readxl#33]
Once you give user control of cell specification (#8), the next question will be if user can control the form of the output. I suspect right now it is always a `tbl_df` with default to a `stringsAsFactors = FALSE` mentality?

Re: header row, will you stick with `col_names =` instead of the more `read-table`-y `header = TRUE/FALSE`? Of course, what you've done with `col_names =` is more powerful.

What about dropping dimensions and returning (named) atomic vector instead of `tbl_df`?

I ask because, as in #8, I'd like to be a consistent as possible in gspreadr.

**Comment by hadley** [comment]
readxl will be consistent with readr and haven, i.e.:

* `col_names` instead of `headers`
* never munge column names with with `make.names`
* don't create factors by default
* always return `tbl_df`s

All of these functions are about returning data frames, so if you want an atomic vector (which I think is a relatively unusual use case), you need to do the subsetting yourself
