### ISSUE TITLE
Read worksheet with only one row

### ISSUE THREAD

**Issue by byzheng** [hadley/readxl#65]
Thanks for this great job fast to read excel files. In my excel file, some worksheets only contain one row (head). This code will give me an error message

```
sheet_i <- read_excel(file, 'log')

Error: Skipped over all data
```

it will be better to generate a data table with 0 row.

**Comment by wdkrnls** [comment]
Could it give a warning instead of an error?

**Comment by byzheng** [comment]
Warning could be a better idea.

**Comment by hadley** [comment]
I think the correct behaviour would be a zero row output

**Comment by TAwosanya** [comment]
Dear Hadley,
Please what do you suggest one can do to solve this problem? My own case is that I have  several excel files with several worksheets in each one. I set up the data loading parameters and I use lapply() to read all worksheets across all files so it might be a little difficult to know which worksheet or files that brings the error. Thanks in advance for your VERY QUICK reply

**Comment by hadley** [comment]
I will resolve this when I'm next working on readxl, which is unlikely to be in the next six weeks.

**Comment by soodoku** [comment]
Dear Hadley,

One more thing, which appears not to have been covered in the comments above: It appears that after the "Error: Skipped over all data", data from subsequent sheets in the file (which have more data) --- is not read in. I suppose it is kind of obvious behavior after the error. But I wanted to make a note of it in the off chance it had escaped your notice.

**Comment by mehmetaergun** [comment]
I got hit by this one too, while trying to import a workbook with 30+ sheets. Happens at 
https://github.com/hadley/readxl/commit/bd63ea583765fe364c9efda8714f3238ed524349#commitcomment-19697741

I'm not fluent in Rcpp nor C++ otherwise I'd gladly provide a pull request. 

When/if you get a chance, would it be possible to turn the stop to warning and also output the name or the index number of the sheet, so this

`
this.sheet <- "my sheet" # second sheet
read_excel(load.file, sheet = this.sheet)
`

would output something like 

`
Rcpp::warning("No data found in sheet: ", sheet_)
# No data found in sheet 'my sheet'
# or
# No data found in sheet 2
`

My workaround for now was to insert a row with all NAs to the single-row sheet but that of course is bad in terms of data integrity and workflow/automation. 

Also, thank you so much for writing this! So happy not to have to depend on java!

**Comment by jennybc** [comment]
This is slight variation of #222, where there's a header row but no data rows.
